version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: webapi1-mssql
    ports:
      - 1433:1433
    volumes:
      - webapi1-volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abc@1234
  seq:
    image: datalust/seq:latest
    container_name: ocelot_seq
    ports:
      - 5342:80
      - 5341:5341
    environment:
      ACCEPT_EULA: "Y"
  consul:
    image: consul:latest
    container_name: ocelot_consul
    ports:
      - 8500:8500
      - 8600:8600
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "5778:5778"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - 3000:3000
    networks:
      - monitor-net
volumes:
  webapi1-volume:
    name: webapi1-volume
networks:
  monitor-net:
    driver: bridge