global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
- job_name: ocelot
  metrics_path: /metrics
  static_configs:  
    - targets: ['192.168.100.67:7048']
- job_name: webapi1
  metrics_path: /metrics
  static_configs:
    - targets: 
      - '192.168.100.67:5087'
      
  